const catalog = [
    {
        id: "cpm",
        name: "Car Parking Multiplayer",
        shortName: "CPM",
        cars: [
            "Toyota AE86",
            "Toyota Supra MK4",
            "Toyota Supra MK5",
            "Toyota GT86",
            "Toyota Chaser JZX100",
            "Toyota Mark II",
            "Toyota Crown",
            "Toyota Corolla",
            "Nissan Silvia S13",
            "Nissan Silvia S14",
            "Nissan Silvia S15",
            "Nissan 180SX",
            "Nissan 240Z",
            "Nissan 300ZX",
            "Nissan 350Z",
            "Nissan 370Z",
            "Nissan Skyline R32",
            "Nissan Skyline R33",
            "Nissan Skyline R34",
            "Nissan GT-R R35",
            "Mazda MX-5 NA",
            "Mazda MX-5 ND",
            "Mazda RX-7 FC",
            "Mazda RX-7 FD",
            "Mazda RX-8",
            "Honda Civic EK9",
            "Honda Civic FD",
            "Honda Civic Type R FN2",
            "Honda Civic Type R FK8",
            "Honda S2000",
            "Honda NSX",
            "Subaru BRZ",
            "Subaru Impreza WRX STI",
            "Mitsubishi Lancer Evolution IX",
            "Mitsubishi Lancer Evolution X",
            "BMW M3 E30",
            "BMW M3 E36",
            "BMW M3 E46",
            "BMW M3 E92",
            "BMW M4 F82",
            "BMW M4 G82",
            "BMW M5 E34",
            "BMW M5 E39",
            "BMW M5 E60",
            "BMW M5 F10",
            "BMW M5 F90",
            "BMW M8",
            "BMW M2",
            "BMW i8",
            "BMW Z4",
            "Mercedes-AMG C63",
            "Mercedes-AMG E63",
            "Mercedes-AMG GT R",
            "Mercedes-AMG G63",
            "Mercedes-Benz S-Class",
            "Mercedes-Benz E-Class",
            "Mercedes-Benz CLS",
            "Audi TT",
            "Audi A4",
            "Audi A5",
            "Audi A6",
            "Audi A7",
            "Audi RS4",
            "Audi RS6",
            "Audi RS7",
            "Audi R8",
            "Lexus IS-F",
            "Lexus GS 350",
            "Lexus LFA",
            "Lexus LC500",
            "Porsche 911",
            "Porsche 911 GT3",
            "Porsche 918 Spyder",
            "Porsche Panamera",
            "Porsche Cayenne",
            "Ferrari 458 Italia",
            "Ferrari 488 GTB",
            "Ferrari F8 Tributo",
            "Ferrari SF90",
            "Ferrari LaFerrari",
            "Lamborghini Gallardo",
            "Lamborghini Huracan",
            "Lamborghini Aventador",
            "Lamborghini Aventador SVJ",
            "Lamborghini Urus",
            "McLaren P1",
            "McLaren 720S",
            "McLaren Senna",
            "Bugatti Veyron",
            "Bugatti Chiron",
            "Koenigsegg Agera R",
            "Koenigsegg Jesko",
            "Pagani Zonda",
            "Pagani Huayra",
            "Chevrolet Camaro",
            "Chevrolet Corvette C6",
            "Chevrolet Corvette C7",
            "Chevrolet Corvette C8",
            "Dodge Charger",
            "Dodge Challenger",
            "Dodge Viper",
            "Ford Mustang",
            "Ford Mustang Boss 302",
            "Ford GT",
            "Ford F-150 Raptor",
            "Toyota Land Cruiser",
            "Toyota Hilux",
            "Jeep Wrangler",
            "Jeep Grand Cherokee",
            "Range Rover Sport",
            "Cadillac Escalade",
            "Chevrolet Tahoe",
            "GMC Sierra",
            "Ram 1500 TRX",
            "Volkswagen Golf MK2",
            "Volkswagen Golf MK7",
            "Volkswagen Scirocco",
            "Volkswagen Passat",
            "Mini Cooper",
            "Alfa Romeo Giulia",
            "Alfa Romeo 4C",
            "Maserati Ghibli",
            "Maserati MC20",
            "Aston Martin Vantage",
            "Aston Martin DB11",
            "Aston Martin Valkyrie",
            "Lotus Elise",
            "Lotus Exige",
            "Rimac Nevera",
            "Zenvo TSR-S",
            "Hennessey Venom GT",
            "DeLorean DMC-12",
            "Chevrolet Impala",
            "Chevrolet Bel Air",
            "Dodge Charger R/T",
            "Ford Falcon",
            "Ford Bronco",
            "Ford F-100",
            "Lada Priora",
            "Lada Niva",
            "Lada VAZ 2114",
            "Tofas Dogan",
            "Tofas Kartal",
            "Mercedes-Benz Sprinter",
            "Ford Transit",
            "Scania R Series",
            "Kenworth T680",
            "DAF Truck",
            "Mercedes-Benz Citaro",
            "Tow Truck"
        ]
    },

    {
        id: "cpm2",
        name: "Car Parking Multiplayer 2",
        shortName: "CPM2",
        cars: [
            "Toyota AE86",
            "Toyota Supra MK4",
            "Toyota Supra MK5",
            "Toyota GR86",
            "Toyota GR Supra",
            "Toyota GT86",
            "Toyota Chaser JZX100",
            "Nissan Silvia S13",
            "Nissan Silvia S14",
            "Nissan Silvia S15",
            "Nissan Skyline R32",
            "Nissan Skyline R33",
            "Nissan Skyline R34",
            "Nissan GT-R R35",
            "Nissan 350Z",
            "Nissan 370Z",
            "Mazda RX-7",
            "Mazda RX-8",
            "Honda Civic",
            "Honda Civic Type R",
            "Honda S2000",
            "Honda NSX",
            "Subaru BRZ",
            "Subaru WRX STI",
            "Mitsubishi Lancer Evolution IX",
            "Mitsubishi Lancer Evolution X",
            "BMW M3 E30",
            "BMW M3 E36",
            "BMW M3 E46",
            "BMW M4",
            "BMW M5",
            "BMW M8",
            "BMW i8",
            "BMW Z4",
            "Mercedes-AMG C63",
            "Mercedes-AMG E63",
            "Mercedes-AMG GT",
            "Mercedes-AMG G63",
            "Audi RS6",
            "Audi RS7",
            "Audi R8",
            "Porsche 911",
            "Porsche 911 GT3",
            "Porsche Taycan",
            "Lamborghini Huracan",
            "Lamborghini Aventador",
            "Lamborghini Urus",
            "Ferrari 488",
            "Ferrari F8",
            "Ferrari SF90",
            "Ferrari LaFerrari",
            "McLaren 720S",
            "McLaren P1",
            "McLaren Senna",
            "Bugatti Veyron",
            "Bugatti Chiron",
            "Koenigsegg Jesko",
            "Pagani Huayra",
            "Chevrolet Corvette C8",
            "Ford Mustang",
            "Dodge Challenger"
        ]
    },

    {
        id: "carx-street",
        name: "CarX Street",
        shortName: "CarX Street",
        cars: [
            "Toyota AE86",
            "Toyota GT86",
            "Toyota GR86",
            "Toyota Supra",
            "Toyota MR2",
            "Nissan Silvia S13",
            "Nissan Silvia S14",
            "Nissan Silvia S15",
            "Nissan 180SX",
            "Nissan Skyline R32",
            "Nissan Skyline R34",
            "Nissan 300ZX",
            "Nissan GT-R",
            "Mazda MX-5",
            "Mazda RX-7",
            "Mazda RX-8",
            "Honda Civic",
            "Honda S2000",
            "Honda NSX",
            "Subaru BRZ",
            "Subaru WRX STI",
            "Mitsubishi Eclipse",
            "Mitsubishi Lancer Evolution",
            "BMW M3 E36",
            "BMW M3 E46",
            "BMW M4",
            "BMW M5",
            "Mercedes-AMG",
            "Audi R8",
            "Audi RS7",
            "Porsche 911",
            "Chevrolet Corvette",
            "Ford Mustang"
        ]
    },

    {
        id: "carx-drift-racing-online",
        name: "CarX Drift Racing Online",
        shortName: "CarX Drift",
        cars: [
            "Toyota Corolla AE86",
            "Mazda MX-5",
            "VAZ 2107",
            "BMW M3 E30",
            "BMW M3 E36",
            "BMW M3 E46",
            "Toyota Celica",
            "Toyota Mark II",
            "Toyota Chaser",
            "Mitsubishi Eclipse",
            "Nissan 180SX",
            "Nissan Silvia S13",
            "Nissan Silvia S14",
            "Nissan Silvia S15",
            "Nissan 300ZX",
            "Nissan Skyline",
            "Nissan GT-R",
            "Nissan Stagea",
            "Mazda RX-7",
            "Toyota GT86",
            "Subaru BRZ",
            "Lexus IS300",
            "BMW M2",
            "BMW M5",
            "Mercedes-Benz CLK",
            "Dodge Challenger",
            "Dodge Charger",
            "Ford Mustang",
            "Chevrolet Camaro",
            "Chevrolet Corvette",
            "Honda NSX",
            "Porsche 911"
        ]
    },

    {
        id: "assoluto-racing",
        name: "Assoluto Racing",
        shortName: "Assoluto",
        cars: [
            "Toyota AE86",
            "Toyota GR86",
            "Toyota GR Supra",
            "Toyota MR2",
            "Toyota Celica",
            "Toyota GT-One",
            "Toyota GR Yaris",
            "Nissan Silvia S13",
            "Nissan Silvia S14",
            "Nissan Silvia S15",
            "Nissan Skyline GT-R R32",
            "Nissan Skyline GT-R R33",
            "Nissan Skyline GT-R R34",
            "Nissan GT-R R35",
            "Nissan R390 GT1",
            "Mazda MX-5",
            "Mazda RX-7",
            "Mazda RX-8",
            "Mazda 787B",
            "Honda Civic",
            "Honda Integra Type R",
            "Honda S2000",
            "Honda NSX",
            "Subaru BRZ",
            "Subaru WRX STI",
            "Mitsubishi Lancer Evolution",
            "BMW M1",
            "BMW M3 E30",
            "BMW M3 E36",
            "BMW M3 E46",
            "BMW M3 E92",
            "BMW M4 F82",
            "BMW M5",
            "BMW Z4",
            "Lexus IS F",
            "Lexus LFA",
            "Porsche 911",
            "Porsche 918 Spyder",
            "Ford GT",
            "Ford Mustang",
            "Chevrolet Corvette",
            "McLaren F1",
            "McLaren P1",
            "Ferrari F40",
            "Ferrari F50",
            "Ferrari 458 Italia",
            "Ferrari LaFerrari",
            "Lamborghini Diablo",
            "Lamborghini Countach",
            "Lamborghini Huracan",
            "Lamborghini Aventador",
            "Pagani Zonda",
            "Bugatti Veyron",
            "Koenigsegg Agera"
        ]
    }
];

module.exports = catalog;